### ISSUE TITLE
Add import uses \ as oppose to : and variable names similar to core lib packages trigger import dialog.

### ISSUE THREAD

**Issue by zhibog** [prime31/Odin-Sublime-Text-Plugin#2]
If you use any name for a struct variable that is in the core lib, like "c" or "fmt", it will ask you to import that package if you try to access a field.

The message will reappear for every character you type. Is there a way to deal with this besides not naming variables the same as core packages?

If you add the import. It will look like import "core\c", instead of import "core:c", that should be an easy fix.

**Comment by prime31** [comment]
Hmm. That is an interesting one. I hadn’t thought about a var name matching a package. I guess an easy fix is to just add a preference to turn it off and never prompt for auto importing.
